# Generated by Django 2.2.7 on 2019-11-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('User', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Pwd', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('Dob', models.DateField()),
                ('mobno', models.IntegerField()),
            ],
        ),
    ]
